import './globals.css';

import type { Metadata } from 'next';
import { fontSans, fontSerif } from '@/assets/fonts';

import Provider from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontSerif.variable} font-sans`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
