import './globals.css';
import '@hashgraph/ui/styles.css';

import type { Metadata } from 'next';

import { fontSans, fontSerif } from '@/assets/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontSerif.variable} font-sans`}>{children}</body>
    </html>
  );
}
