import { colors } from './';
import { ThemeColors } from './types';

export const defaultLightColors: ThemeColors = {
  base: colors.base.black,
  background: {
    DEFAULT: colors.base.white,
    primary: colors.gray[25],
    secondary: colors.gray[900],
    light: colors.gray[100],
    disabled: colors.gray[200],
    tertiary: colors.base.white,
    quaternary: colors.base.white,
  },
  foreground: {
    DEFAULT: colors.gray[900],
    primary: colors.gray[900],
    button: colors.gray[25],
    secondary: colors.gray[500],
    disabled: colors.gray[300],
    error: colors.error[500],
    warning: colors.warning[500],
    success: colors.success[500],
  },
  active: colors.gray[100],
  border: {
    DEFAULT: colors.gray[200],
    secondary: colors.gray[300],
  },
  button: {
    DEFAULT: colors.brand[500],
    focus: colors.brand[600],
    hover: colors.brand[600],
    active: colors.brand[600],
  },
  input: {
    DEFAULT: colors.base.white,
    border: colors.gray[300],
  },
  divider: colors.gray[200],
  overlay: colors.gray[950],
  brand: colors.brand,
  tertiary: colors.orange,
  gray: colors.gray,
  secondary: colors.blue,
  warning: colors.warning,
  error: colors.error,
  success: colors.success,
  disabled: colors.gray[400],
  muted: colors.gray[400],
};

export const defaultDarkColors: ThemeColors = {
  base: colors.base.white,
  background: {
    DEFAULT: colors.gray[950],
    primary: colors.gray[950],
    secondary: colors.gray[950],
    light: colors.gray[700],
    disabled: colors.gray[800],
    tertiary: colors.gray[800],
    quaternary: colors.gray[600],
  },
  foreground: {
    DEFAULT: colors.gray[25],
    primary: colors.gray[25],
    button: colors.gray[100],
    secondary: colors.gray[500],
    disabled: colors.gray[700],
    error: colors.error[300],
    warning: colors.warning[300],
    success: colors.success[300],
  },
  active: colors.gray[800],
  border: {
    DEFAULT: colors.gray[800],
    secondary: colors.gray[700],
  },
  button: {
    DEFAULT: colors.brand[300],
    focus: colors.brand[200],
    hover: colors.brand[200],
    active: colors.brand[200],
  },
  input: {
    DEFAULT: colors.gray[900],
    border: colors.gray[700],
  },
  divider: colors.gray[800],
  overlay: colors.gray[950],
  brand: colors.brand,
  tertiary: colors.orange,
  gray: colors.gray,
  secondary: colors.blue,
  warning: colors.warning,
  error: colors.error,
  success: colors.success,
  disabled: colors.gray[500],
  muted: colors.gray[400],
};
